USE [master]
GO
/****** Object:  Database [cpwrSecurity]    Script Date: 05/25/2011 10:54:58 ******/
CREATE DATABASE [cpwrSecurity] ON  PRIMARY 
( NAME = N'cpwrSecurity', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\cpwrSecurity.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'cpwrSecurity_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\cpwrSecurity_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'cpwrSecurity', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cpwrSecurity].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [cpwrSecurity] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [cpwrSecurity] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [cpwrSecurity] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [cpwrSecurity] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [cpwrSecurity] SET ARITHABORT OFF 
GO
ALTER DATABASE [cpwrSecurity] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [cpwrSecurity] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [cpwrSecurity] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [cpwrSecurity] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [cpwrSecurity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [cpwrSecurity] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [cpwrSecurity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [cpwrSecurity] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [cpwrSecurity] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [cpwrSecurity] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [cpwrSecurity] SET  ENABLE_BROKER 
GO
ALTER DATABASE [cpwrSecurity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [cpwrSecurity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [cpwrSecurity] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [cpwrSecurity] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [cpwrSecurity] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [cpwrSecurity] SET  READ_WRITE 
GO
ALTER DATABASE [cpwrSecurity] SET RECOVERY FULL 
GO
ALTER DATABASE [cpwrSecurity] SET  MULTI_USER 
GO
ALTER DATABASE [cpwrSecurity] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [cpwrSecurity] SET DB_CHAINING OFF 